### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ryrl9703** [XWangLabTHU/ARIC#2]
---------------------------------------------
--------------WELCOME TO ARIC----------------
---------------------------------------------
Data reading finished!
ARIC Engines Start, Please Wait......
100%|███████████████████████████████████████████| 50/50 [02:44<00:00,  3.29s/it]
Deconvo Results Saving!
Finished!

Cannot find the output results file?  Why?

**Comment by Honchkrow** [comment]
Hello @ryrl9703 ,
    Thanks for using ARIC again!
    If you are running ARIC with out specifing the output file name in parameter 'save_path', the results will be saved in a csv file named "BulkFilePrefix_prop.csv". For example, if you are running the demo data, the output file will be "mix_prop.csv". If you want to get the markers, please set the parameter "selected_marker=True". 

shaway

**Comment by ryrl9703** [comment]
> Hello @ryrl9703 ,
> Thanks for using ARIC again!
> If you are running ARIC with out specifing the output file name in parameter 'save_path', the results will be saved in a csv file named "BulkFilePrefix_prop.csv". For example, if you are running the demo data, the output file will be "mix_prop.csv". If you want to get the markers, please set the parameter "selected_marker=True".
> 
> shaway


Thank you for your reply, it can work well now.
